# Override these properties in an external properties file or environment variable.
# See https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html

spring:
  application:
    # The name of the spring application.
    name: gateway

    # Dashboard config.
    thymeleaf:
      cache: false
      enabled: true
      prefix: classpath:/templates/
      suffix: .html

server:
  # The HTTP port to listen to when using an embedded Tomcat server.
  port: 8181

  # The AJP port to listen to when using an embedded Tomcat server. Leave blank if AJP connections
  # are not needed.
  # ajp:
  #   port:

# Default Elasticsearch gateway settings. These can be overridden in the ES route config for each
# tenant.
es:
  # The names of CollectionSpace record types that are publicly accessible through Elasticsearch.
  # This should be a comma-separated list of tenant-unqualified record types. If no value is given,
  # defaults to 'CollectionObject'.
  allowedRecordTypes: CollectionObject

  # For each publicly accessible record type, specify the name of the Elasticsearch field to check to
  # see if a specific record is published, and should be publicly accessible. Each record type
  # specified in es.allowedRecordTypes should have a publishToField configured. Media records should
  # also have a publishToField configured, even if Media is not specified in es.allowedRecordTypes.
  # This allows the gateway to make an Elaticsearch query to check if a media record is published
  # when an attempt is made to retrieve media through the REST API.
  # Typically, values will have the format <schema>:<field name>.shortid
  # If no value is given, the record is effectively not publicly accessible (technically, the
  # default value is 'collectionspace_core:publishToList.shortid', but that field currently does
  # not exist, as of CSpace 8.0).
  recordTypes:
    CollectionObject:
      publishToField: collectionobjects_common:publishToList.shortid
    Media:
      publishToField: media_common:publishToList.shortid

  # Values that may exist in the Publish To field for records to be publicly accessible.
  # This should be a comma-separated list of short ids. Use '*' if any value in the Publish To
  # field is acceptable (including 'none'). Defaults to 'all' if not specified.
  allowedPublishToValues: cspacepub,all

zuul:
  # routes:
  #   core-cspace-services:
  #     path: /core/cspace-services/**

  #     # The URL of the CollectionSpace REST API.
  #     url: http://localhost:8180/cspace-services

  #     # Credentials to use for connecting to the CollectionSpace REST API.
  #     username: reader@core.collectionspace.org
  #     password: reader

  #   core-es:
  #     path: /core/es/**

  #     # The URL of the Elasticsearch cluster (including index).
  #     url: http://localhost:9200/nuxeo

  #   materials-cspace-services:
  #     path: /materials/cspace-services/**
  #     url: http://localhost:8180/cspace-services
  #     username: reader@materials.collectionspace.org
  #     password: reader

  #   materials-es:
  #     path: /materials/es/**
  #     url: http://localhost:9200/materials

  #     # Override default ES settings.
  #     allowedRecordTypes: CollectionObject,Materialitem
  #     recordTypes:
  #       CollectionObject:
  #         publishToField: collectionobjects_common:publishToList.shortid
  #       Materialitem:
  #         publishToField: materials_common:publishToList.shortid
  #       Media:
  #         publishToField: media_materials:publishToList.shortid
  #     allowedPublishToValues: materialorder,all
